allowBuilds:
  esbuild: true
minimumReleaseAgeExclude:
  - '@takumi-rs/core-darwin-arm64@2.7.1'
  - '@takumi-rs/core-darwin-x64@2.7.1'
  - '@takumi-rs/core-linux-arm64-gnu@2.7.1'
  - '@takumi-rs/core-linux-arm64-musl@2.7.1'
  - '@takumi-rs/core-linux-x64-gnu@2.7.1'
  - '@takumi-rs/core-linux-x64-musl@2.7.1'
  - '@takumi-rs/core-win32-arm64-msvc@2.7.1'
  - '@takumi-rs/core-win32-x64-msvc@2.7.1'
  - '@takumi-rs/core@2.7.1'
  - '@takumi-rs/helpers@2.7.1'
  - '@takumi-rs/wasm@2.7.1'
  - takumi-js@2.7.1
